name: truckcoal_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cloud_firestore: ^5.6.8
  firebase_core: ^3.13.1
  cloud_firestore_web: ^4.4.8
  intl: ^0.20.2
  shared_preferences: ^2.0.9
  excel: ^2.0.7
  path_provider: ^2.0.8
  printing: ^5.3.0
  open_file: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
